on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    - run: echo "${{ secrets.FTP_SERVER }}"
    - run: echo "${{ secrets.FTP_USERNAME }}"
    - run: echo "${{ secrets.ftp_password_WEAMA }}"
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_SERVER }}
        protocol: sftp
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.ftp_password_WEAMA }}
        port: 22
        args: '-o ConnectTimeout=5'
