on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
   permissions:
      issues: write
      pull-requests: write
   steps:
      - uses: actions/stale@v5   
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: 159.65.214.179
        username: root
        password: ${{ secrets.ftp_password_WEAMA }}
        port: 22
        server-dir: /var/www/
